name: Run Python Script

on:
  push:
    branches:
      - main  # or 'master' or any branch you use
  schedule:
    # Runs every hour from 9:00 to 20:00 (UTC)
    - cron: '0 8-19 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: seen_matches.pkl
        key: padel-cache-${{ runner.os }}
        restore-keys: padel-cache-

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # or any version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true  # optional

    - name: Run script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python main.py

    - name: Save cache
      uses: actions/cache/save@v3
      if: always()
      with:
        path: seen_matches.pkl
        key: padel-cache-${{ runner.os }}-${{ runner.arch }}-${{ github.run_id }}-${{ github.run_attempt }}